In [1]:
import numpy as np

random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.3383768  0.50103303 0.08532973]
  [0.37715546 0.66927746 0.56321675]
  [0.87326186 0.61573032 0.10021944]]

 [[0.44521196 0.63082208 0.86432305]
  [0.72520409 0.11337977 0.77521262]
  [0.58604413 0.89357113 0.47538658]]

 [[0.89311216 0.72524529 0.30788068]
  [0.11035892 0.79476895 0.41264245]
  [0.35277907 0.53286753 0.36657973]]]


In [2]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill the values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [3]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern with alternating 1s and 0s
matrix[1::2, ::2] = 1  # Rows 2, 4, 6, 8 (0-based indexing) and even columns
matrix[::2, 1::2] = 1  # Rows 1, 3, 5, 7 (0-based indexing) and odd columns

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
import numpy as np

# Create a random 5x5 matrix
random_matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the matrix
mean = random_matrix.mean()
std_dev = random_matrix.std()

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

print("Random Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)


Random Matrix:
[[0.0865395  0.08880402 0.36545217 0.15614668 0.59199141]
 [0.15071065 0.80990425 0.39395149 0.0496444  0.11569293]
 [0.03768767 0.82897224 0.07974946 0.23842043 0.44665377]
 [0.3325143  0.69995833 0.35827308 0.22782453 0.00582276]
 [0.40067969 0.51758216 0.09089497 0.41042001 0.70083707]]

Normalized Matrix:
[[-0.9761785  -0.96700086  0.1541968  -0.69407499  1.07231347]
 [-0.71610609  1.95546911  0.26969865 -1.1257067  -0.85802567]
 [-1.17416485  2.0327477  -1.0036971  -0.36063654  0.48329011]
 [ 0.02070646  1.50988105  0.12510145 -0.40357952 -1.30330673]
 [ 0.29696667  0.77074818 -0.95852668  0.33644218  1.5134424 ]]


In [5]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)

print(common_values)


[3 4 5]


In [6]:
import datetime

# Get today's date
today = datetime.date.today()

# Calculate yesterday and tomorrow
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)

# Format the dates as strings (optional)
today_str = today.strftime('%Y-%m-%d')
yesterday_str = yesterday.strftime('%Y-%m-%d')
tomorrow_str = tomorrow.strftime('%Y-%m-%d')

# Print the dates
print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


In [7]:
import numpy as np

# Create two random arrays A and B (replace these with your actual arrays)
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


In [8]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector with Maximum Value Replaced:")
print(random_vector)


Random Vector with Maximum Value Replaced:
[0.55581626 0.64849335 0.05195339 0.31017281 0.52417463 0.54319729
 0.41195444 0.30912664 0.         0.27151654]


In [9]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

for item in my_array:
    print(item)


1
2
3
4
5


In [10]:
import numpy as np

# Create a sample matrix (replace this with your actual matrix)
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the original matrix
normalized_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)

print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [11]:
import numpy as np

# Given vector
original_vector = np.array([1, 2, 3, 4, 5])

# Index vector (contains the indices where 1 should be added)
index_vector = np.array([1, 3, 2, 1, 4])

# Create a unique index vector to avoid repeated indices
unique_indices, unique_counts = np.unique(index_vector, return_counts=True)

# Add 1 to the corresponding elements in the original vector
original_vector[unique_indices] += 1

print("Original Vector:")
print(original_vector)


Original Vector:
[1 3 4 5 6]


In [12]:
import numpy as np

# Create two matrices (replace these with your actual matrices)
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

# Compute the dot product of the two matrices
dot_product = np.dot(matrix1, matrix2)

# Get the diagonal of the dot product
diagonal = np.diag(dot_product)

print("Dot Product:")
print(dot_product)

print("\nDiagonal of Dot Product:")
print(diagonal)


Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of Dot Product:
[30 69 90]


In [13]:
import numpy as np

# Replace this with your actual NumPy array
my_array = np.array([7, 4, 5, 3, 3, 6, 5, 8, 1, 5, 1, 1, 8, 7, 4, 5, 8, 7, 3, 2, 3, 6, 1, 5, 3, 3, 7, 5, 3, 8, 7, 1, 4, 1, 4, 1, 1, 1, 6, 6, 8, 6, 8, 3, 4, 4, 7, 8, 0])

# Find the most common element (mode) using NumPy
most_common_value = np.bincount(my_array).argmax()

# Count the occurrences of the most common value
most_common_count = np.sum(my_array == most_common_value)

print("Most Common Value:", most_common_value)
print("Count:", most_common_count)


Most Common Value: 1
Count: 9


In [14]:
import numpy as np

# Create a sample array (replace this with your actual array)
my_array = np.array([7, 4, 5, 3, 6, 8, 1, 2, 9, 0])

# Get the indices that would sort the array in descending order
sorted_indices = np.argsort(my_array)[::-1]

# Get the n largest values by indexing the sorted array
n_largest = my_array[sorted_indices[:n]]

print(f"{n} Largest Values:", n_largest)


NameError: name 'n' is not defined

In [15]:
import numpy as np

# Create a sample array (replace this with your actual array)
my_array = np.array([7, 4, 5, 3, 6, 8, 1, 2, 9, 0])

# Get the n largest values using numpy.partition
n_largest = np.partition(my_array, -n)[-n:]

print(f"{n} Largest Values:", n_largest)


NameError: name 'n' is not defined

In [16]:
#question 15
import numpy as np

# Create a regular array (list of tuples)
regular_array = [(1, 'Alice', 25),
                 (2, 'Bob', 30),
                 (3, 'Charlie', 35)]

# Define the data type for the record array
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

# Create the record array
record_array = np.array(regular_array, dtype=dtype)

print(record_array)


[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 35)]


In [17]:
import numpy as np

# Create a sample 2D array (replace this with your actual array)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows 1 and 2 (0-based indexing)
array[1], array[2] = array[2].copy(), array[1].copy()

print("Array after swapping rows:")
print(array)


Array after swapping rows:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [18]:
import numpy as np

# Create a 1D array (replace this with your actual array)
arr = np.array([23, 4, 121, 23, 22, 67, 686, 434, 123])

# Reshape the array to a 2D array with 3 rows and 3 columns
reshaped_arr = arr.reshape(3, 3)

# Alternatively, you can use numpy.newaxis
# reshaped_arr = arr[:, np.newaxis]

print("Original 1D Array:")
print(arr)

print("\nReshaped 2D Array:")
print(reshaped_arr)


Original 1D Array:
[ 23   4 121  23  22  67 686 434 123]

Reshaped 2D Array:
[[ 23   4 121]
 [ 23  22  67]
 [686 434 123]]
